env:
  browser: true
  node: true
  commonjs: true
  es6: true
  mocha: true
extends:
- standard
- standard-react
- plugin:flowtype/recommended
- plugin:import/errors
- plugin:import/warnings
- plugin:jsx-a11y/recommended
parser: babel-eslint
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
- flowtype
- import
- jsx-a11y
rules:
  comma-dangle:
  - error
  - always-multiline
  key-spacing:
  - error
  - align: value
  no-multi-spaces:
  - error
  - exceptions:
      VariableDeclarator: true
      ImportDeclaration: true
  no-duplicate-imports:
  - off
  import/no-duplicates:
  - error
  - always
  flowtype/semi:
  - error
  - never
  flowtype/delimiter-dangle:
  - error
  - always-multiline
  flowtype/object-type-delimiter:
  - error
  - comma
