language: node_js
node_js:
- 6
sudo: false
matrix:
  fast_finish: true
  include:
  - os: osx
    osx_image: xcode8.2
  - os: linux
    dist: trusty
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
script:
- $(npm bin)/npm-run-all --parallel test build
after_success:
- test "${TRAVIS_OS_NAME}" = "osx" &&
  (test "${TRAVIS_TAG}" != "pre-release" && test "${TRAVIS_BRANCH}" = "master") &&
  test "${TRAVIS_PULL_REQUEST}" = "false" &&
  brew tap tcnksm/ghr &&
  brew install ghr &&
  yarn run package &&
  ghr --username $GH_USER --token $GH_TOKEN --recreate --prerelease --debug pre-release release/mac/tomatone-*.dmg
- test "${TRAVIS_OS_NAME}" = "osx" &&
  (test "${TRAVIS_TAG}" && (test "${TRAVIS_TAG}" != "pre-release")) &&
  yarn run package:release
