osx_image: xcode7.3
sudo: required
dist: trusty
language: c
matrix:
  include:
  - os: osx
  # - os: linux
  #   env: CC=clang CXX=clang++ npm_config_clang=1
  #   compiler: clang
cache:
  yarn: true
  directories:
  - node_modules
  - "$HOME/.electron"
  - "$HOME/.cache"
addons:
  # apt:
  #   packages:
  #   - libgnome-keyring-dev
  #   - icnsutils
before_install:
- nvm install 6
- nvm use 6
- curl -o- -L https://yarnpkg.com/install.sh | bash
- export PATH=$HOME/.yarn/bin:$PATH
install:
- yarn
script:
- yarn test
- yarn run build
after_success:
- ((test "${TRAVIS_TAG}" != "pre-release") && (test "${TRAVIS_BRANCH}" = "master") && (test "${TRAVIS_PULL_REQUEST}" = "false")) &&
  yarn run package:prerelease
- (test "${TRAVIS_TAG}" && (test "${TRAVIS_TAG}" != "pre-release")) &&
  yarn run package:release
